### ISSUE TITLE
Not spawning forage

### ISSUE THREAD

**Issue by Mimir0** [Esca-MMC/FarmTypeManager#22]
As the title says farm type manager isn't spawning any forage or hardwood. Here's log- 
https://smapi.io/log/c98b64f6fd2140e3ac1806d183e4ff8a

**Comment by Esca-MMC** [comment]
Sorry about the delay. For future reference, this seems like an issue with configuration rather than the mod's code, so I'd recommend asking for help in one of Stardew's communities (Discord, Reddit, etc).

If it's still a problem, or if anyone else has similar issues, please post another log.
